name: flutter_chat_app
description: "Application de chat en temps réel avec Firebase."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3

  # State management
  provider: ^6.1.2

  # UI / UX
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  shared_preferences: ^2.3.2

  # Utils
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/