// File generated by FlutterFire CLI.
// Run `flutterfire configure` to regenerate this file with your own project.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ⚠️ REMPLACEZ CES VALEURS par celles de votre projet Firebase

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLZ5YY__wOHuBSYBOBFqSPKD5kLMgqerM',
    appId: '1:601218547398:web:27e80939b972aa7c4761c7',
    messagingSenderId: '601218547398',
    projectId: 'wechat3008-634cd',
    authDomain: 'wechat3008-634cd.firebaseapp.com',
    storageBucket: 'wechat3008-634cd.firebasestorage.app',
    measurementId: 'G-N5S1VRNZ8Z',
  );

  // (via `flutterfire configure` ou la console Firebase).

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC85dSAPczS4PDx_yoed0lZ7LSIgqEmTzw',
    appId: '1:601218547398:ios:c26dcd8e6e578b554761c7',
    messagingSenderId: '601218547398',
    projectId: 'wechat3008-634cd',
    storageBucket: 'wechat3008-634cd.firebasestorage.app',
    iosClientId: '601218547398-e7n92igqkkt0230j06cfvpnniuud8qrm.apps.googleusercontent.com',
    iosBundleId: 'com.misspurple.flutterchatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );
}